################### Merakibeat Configuration Example #########################

############################# Merakibeat ######################################

merakibeat:
  # Defines how often an event is sent to the output
  period: 10s
  merakihost: https://api.meraki.com
  merakikey: 093b24e85df15a3e66f1fc359f4c48493eaa1b73
  merakinewtorkids: ["ABC1", "ABC2"]
  merakiorgid: "549236"
  nwconnstat: 1
  nwlatencystat: 1
  devconnstat: 0
  devlatencystat: 0
  clconnstat: 0
  cllatencystat: 0
#================================ General =====================================

# The name of the shipper that publishes the network data. It can be used to group
# all the transactions sent by a single shipper in the web interface.
name: MerakiHealth

# The tags of the shipper are included in their own field with each
# transaction published.
#tags: ["service-X", "web-tier"]

# Optional fields that you can specify to add additional information to the
# output.
#fields:
#  env: staging



#================================ Outputs =====================================

# Configure what output to use when sending the data collected by the beat.

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["localhost:9200"]

  # Optional protocol and basic auth credentials.
  #protocol: "https"
  #username: "elastic"
  #password: "changeme"

#================================ Logging =====================================

# Sets log level. The default log level is info.
# Available log levels are: error, warning, info, debug
#logging.level: debug

# At debug level, you can selectively enable logging only for some components.
# To enable all selectors use ["*"]. Examples of other selectors are "beat",
# "publish", "service".
#logging.selectors: ["*"]

