version: '2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  mearkibeat:
    image: npateriyainsecure/merakibeat
    volumes:
      - ./config/merakibeat.yml:/plugin/merakibeat.yml:ro
    networks:
      - elk
    depends_on:
      - elasticsearch
      - merakimock

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.0
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  merakimock:
    image: npateriyainsecure/merakimock
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
